version: "3.3"
services:
  postgis:
    image: kartoza/postgis:10.0-2.4
    ports:
      - 5432:5432
    entrypoint: >
      bash -c "wget -N -P / https://raw.githubusercontent.com/jancelin/docker-postgis/master/setup-database.sh &&
               wget -N -P /home https://github.com/jancelin/docker-postgis/raw/master/geopoppy.sql &&
               /docker-entrypoint.sh"
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_USER=docker
      - POSTGRES_DBNAME=geopoppy
      - POSTGRES_DUMP=geopoppy.sql
